### ISSUE TITLE
Running with Python 3.10

### ISSUE THREAD

**Issue by krishnatrivedi** [nicolasbrailo/ChromecasticSlideshow#1]
Greetings!

I was hoping to see if this could be refactored to work with Python 3.10. I've been running into a lot of problems trying to get pipenv working.

Thanks in advance,
KT

**Comment by nicolasbrailo** [comment]
Hi @krishnatrivedi ! From a quick glance, it doesn't look like there should be anything stopping this from running in Python 3, as all the dependencies look like alive projects.

Can you list what you've tried, and what kind of problems you've run into?

**Comment by krishnatrivedi** [comment]
Here's what I tried:

`$ pipenv --python 3.10
Creating a virtualenv for this project...
Pipfile: /home/krishna/Desktop/git/ChromecasticSlideshow/Pipfile
Using /usr/bin/python3 (3.10.12) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.10.12.final.0-64 in 1768ms
  creator CPython3Posix(dest=/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/krishna/.local/share/virtualenv)
    added seed packages: pip==23.3.2, setuptools==69.0.3, wheel==0.42.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator`

`
✔ Successfully created virtual environment!
Virtualenv location: /home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh
Warning: Your Pipfile requires python_version 3.6, but you are using 3.10.12 (/home/k/.local/share/v/C/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
`


Then, tried to run, but got this error:

`$ pipenv run python ./chromecastic_slideshow.py -H 192.168.1.208 -c Living-Kitchen /media/saraswati/Pictures/pictures_by_year/
Traceback (most recent call last):
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/./chromecastic_slideshow.py", line 1, in <module>
    from chromecastic_slideshow import ChromecasticSlideshow
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/__init__.py", line 1, in <module>
    from .image_providers import FSRandomImager, FSToWebRandomImager
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/image_providers.py", line 41, in <module>
    import flask
ModuleNotFoundError: No module named 'flask'
`


Solved it by installing flask: 

`$ pipenv install flask
Installing flask...
Resolving flask...
✔ Installation Succeeded
Installing dependencies from Pipfile.lock (f060ae)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
`


OK, then tried running again, but got a different error:

`$ pipenv run python ./chromecastic_slideshow.py -H 192.168.1.208 -c Living-Kitchen /media/saraswati/Pictures/pictures_by_year/
Traceback (most recent call last):
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/./chromecastic_slideshow.py", line 1, in <module>
    from chromecastic_slideshow import ChromecasticSlideshow
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/__init__.py", line 1, in <module>
    from .image_providers import FSRandomImager, FSToWebRandomImager
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/image_providers.py", line 41, in <module>
    import flask
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/jinja2/environment.py", line 16, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/jinja2/tests.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
`

Googling around, found this at stackoverflow:  https://stackoverflow.com/questions/69381312/importerror-cannot-import-name-mapping-from-collections-using-python-3-10

It looks like the invocation of collections has changed in python 3.10. So I tried manually editing the `~/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/jinja2/tests.pyjinja2/test.py` file with the new syntax:  


`from collections.abc import Mapping
`

Then, had to edit the same this file:

` ~/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/flask/sessions.py
`

Also in this file: `~/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py`

I had to make this change:

`import collections.abc as collections`

Finally, I think I got it working. But then ran into this error and now I'm stumped:

`$ pipenv run python ./chromecastic_slideshow.py -H 192.168.1.208 -c Living-Kitchen /media/saraswati/Pictures/pictures_by_year/
2024-01-03 12:55:21,346 - ChromecasticSlideshow - INFO - Loading images from /media/saraswati/Pictures/pictures_by_year/
Traceback (most recent call last):
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/./chromecastic_slideshow.py", line 67, in <module>
    cs = ChromecasticSlideshow(logger, args.root_path, args.allowed_extensions,
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/__init__.py", line 8, in __init__
    self.img_server = FSToWebRandomImager(FSRandomImager(root_path, allowed_extensions),
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/image_providers.py", line 62, in __init__
    self.flask_app = Flask(__name__)
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/flask/app.py", line 558, in __init__
    self.add_url_rule(
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/flask/app.py", line 1216, in add_url_rule
    self.url_map.add(rule)
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/werkzeug/routing.py", line 1562, in add
    rule.bind(self)
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/werkzeug/routing.py", line 711, in bind
    self.compile()
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/werkzeug/routing.py", line 767, in compile
    self._build = self._compile_builder(False)
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/werkzeug/routing.py", line 1128, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "/home/krishna/.local/share/virtualenvs/ChromecasticSlideshow-60N5k3fh/lib/python3.10/site-packages/werkzeug/routing.py", line 1119, in compile
    co = types.CodeType(*code_args)
TypeError: code expected at least 14 arguments, got 13
`



Any thoughts would be appreciated.

Thanks and awesome work on this. I'll look into submitting a PR for the collections changes for later versions of python, if that's ok with you.

Thanks again,
KT

**Comment by krishnatrivedi** [comment]
Actually, seemed to get it working by installing werkzeug:

`$ pipenv install  werkzeug
Installing werkzeug...
Resolving werkzeug...
Added werkzeug to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock (f060ae) out of date, updating to (703e48)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (85acd78033d0eed1177e391212d14cbb653025b018f4029fb3cb575084703e48)!
Installing dependencies from Pipfile.lock (703e48)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run`

It looks to be running, but getting this error:

`$ pipenv run python ./chromecastic_slideshow.py -H 192.168.1.208 -c Living-Kitchen /media/saraswati/Pictures/pictures_by_year/2024-01-03 13:17:00,086 - ChromecasticSlideshow - INFO - Loading images from /media/saraswati/Pictures/pictures_by_year/2024-01-03 13:17:00,336 - ChromecasticSlideshow - INFO - Looking for all Chromecasts in the network
 * Serving Flask app 'chromecastic_slideshow.image_providers'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://192.168.1.208:46301
Press CTRL+C to quit
Traceback (most recent call last):
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/./chromecastic_slideshow.py", line 67, in <module>
    cs = ChromecasticSlideshow(logger, args.root_path, args.allowed_extensions,
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/__init__.py", line 16, in __init__
    self.cc_driver = ChromecastDriver(logger, target_chromecast_name,
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/chromecast_driver.py", line 47, in __init__
    self.cast = next(cc for cc in all_casts
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/chromecast_driver.py", line 48, in <genexpr>
    if cc.device.friendly_name == target_chromecast_name)
AttributeError: 'list' object has no attribute 'device'
`

I'll keep debugging, but if you have any suggestions, let me know. 

Thanks!

**Comment by nicolasbrailo** [comment]
@krishnatrivedi thanks for the logs! The first issues would seem to be a missing `pipenv sync` before the first run. The second one, looks like a problem in the dependency graph of Flask (sometime in the last 5 years, the pipfile.lock seemed to devolve into non compatible dependencies). The last error ('list' object has no attribute 'device') could be an actual problem - that seems to point to a change in the interface of pychromecast, which wouldn't be too surprising.

I'd advise trying to rebuild all deps from more modern versions (eg running 'pipenv lock', or removing the existing Pipenv.lock and and installing all deps again (probably `pipenv install pychromecast apscheduler flask requests`.

If you try to do pipenv lock again, does it fix all the issues?

**Comment by nicolasbrailo** [comment]
A quick test shows that the interface of pychromecast indeed changed at some point:

```
$ python
Python 3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychromecast as pc
>>> pc.get_chromecasts()
([], <pychromecast.discovery.CastBrowser object at 0x7f1011feb710>)
>>>
```

In theory, changing [this line](https://github.com/nicolasbrailo/ChromecasticSlideshow/blob/master/chromecastic_slideshow/chromecast_driver.py#L45) to `all_casts = pychromecast.get_chromecasts()[0]` might be enough to upgrade the deps of the project (assuming no other interface changes in 5 years!)

Of course, I don't have a nearby Chromecast to test it, so I can't be entirely sure :)

**Comment by krishnatrivedi** [comment]
Steps:

1. Change the line to add [0] as you recommended
2. Deleted the Pipfile.lock file
3. Ran this: 
` $ pipenv install pychromecast apscheduler flask requests werkzeug
Installing pychromecast...
Resolving pychromecast...
✔ Installation Succeeded
Installing apscheduler...
Resolving apscheduler...
✔ Installation Succeeded
Installing flask...
Resolving flask...
✔ Installation Succeeded
Installing requests...
Resolving requests...
✔ Installation Succeeded
Installing werkzeug...
Resolving werkzeug...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (85acd78033d0eed1177e391212d14cbb653025b018f4029fb3cb575084703e48)!
Installing dependencies from Pipfile.lock (703e48)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
`
4. This is the output:
`$ pipenv run python ./chromecastic_slideshow.py -H 192.168.1.208 -c Living-Kitchen /media/saraswati/Pictures/pictures_by_year/
2024-01-03 15:03:18,067 - ChromecasticSlideshow - INFO - Loading images from /media/saraswati/Pictures/pictures_by_year/
2024-01-03 15:03:18,310 - ChromecasticSlideshow - INFO - Looking for all Chromecasts in the network
 * Serving Flask app 'chromecastic_slideshow.image_providers'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://192.168.1.208:44739
Press CTRL+C to quit
Traceback (most recent call last):
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/./chromecastic_slideshow.py", line 67, in <module>
    cs = ChromecasticSlideshow(logger, args.root_path, args.allowed_extensions,
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/__init__.py", line 16, in __init__
    self.cc_driver = ChromecastDriver(logger, target_chromecast_name,
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/chromecast_driver.py", line 47, in __init__
    self.cast = next(cc for cc in all_casts
  File "/home/krishna/Desktop/git/ChromecasticSlideshow/chromecastic_slideshow/chromecast_driver.py", line 48, in <genexpr>
    if cc.device.friendly_name == target_chromecast_name)
AttributeError: 'Chromecast' object has no attribute 'device'
`

**Comment by krishnatrivedi** [comment]
In addition, not sure if I'm doing this right. When I try to connect to the URL via a browser on my local network, I get this error:

`
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
`

The terminal log shows this:
`
192.168.1.208 - - [03/Jan/2024 15:39:43] "GET / HTTP/1.1" 404 -
192.168.1.208 - - [03/Jan/2024 15:39:43] "GET /favicon.ico HTTP/1.1" 404 -
`
Thanks in advance for all your help!

KT

**Comment by nicolasbrailo** [comment]
@krishnatrivedi that looks fairly good, thanks for the patience to get here! At this point, the project is running (and it'd be good to submit a PR, if you ever get the time to do so) but it's broken because the interface of pychromcast changed. Now, we need to go line by line in ChromecastDriver.py and figure out what changed. This is likely a couple hours of work, but it does require a Chromecast, and I don't have one set up.

If I find one in my spare parts box I'll fix the changes, but can't make a promise! 

Ps: For the webserver, try going to 192.168.1.208/get_random_image/<random_number> - there is no page configured for the / path.

**Comment by krishnatrivedi** [comment]
Thanks @nicolasbrailo ! I can see random pictures from the URL provided. How can I get the Chromecast to see that?  I can't seem to find anything in the Home app on my phone. Or does the script push the pics to the Chromecast? 

I appreciate all the help. I just had a spare Chromecast and a spare monitor and wanted to show pictures during a party or just for fun with minimal hardware.

**Comment by krishnatrivedi** [comment]
Some googling around, it seems others are having same issue:  https://github.com/keredson/gnomecast/issues/171

My python is rusty, but I'll do some debugging on my own to figure this out.

Thanks!

**Comment by nicolasbrailo** [comment]
> does the script push the pics to the Chromecast?

What this script does, is

1. Start a webserver that can show random pictures on a url (192.168.1.208/get_random_image/<random>, in your case)
2. Ask a Chromecast to load said URL
3. Every N seconds, ask the Chromecast to reload that URL (to show a new picture)
4. Listen to notifications from the device, so that it can stop asking it load pictures when someone is playing media (otherwise it would override any other attempt at playing media every N seconds)

So it doesn't really push anything to the CC, it just says "hey, CC, go and load this page". The script itself is pretty trivial - as long as we can change the usage of pychromecast to match its new interface, it's very likely to continue working forever.

**Comment by nicolasbrailo** [comment]
@krishnatrivedi can you give it a try with the latest commit?

**Comment by krishnatrivedi** [comment]
@nicolasbrailo you are a rockstar! It works! I just had to run the following to get it going:

`pipenv -rm`

`pipenv install pychromecast apscheduler flask requests werkzeug`

`pipenv run python ./chromecastic_slideshow.py -H 192.168.1.xxx -c {name-of-Chromecast} /path-to-pics`

Thanks again for all your help!

**Comment by krishnatrivedi** [comment]
Another question, is there a way to display the path of the image being displayed to the Chromecast? Kind of an overlay of it on the image in small font?

**Comment by nicolasbrailo** [comment]
> is there a way to display the path of the image being displayed to the Chromecast? Kind of an overlay of it on the image in small font?

Not currently implemented. Right now we ask the Chromecast to load a raw image (ie not a webpage: just an image). To have an overlay on the image, there are two options:

1. Figure out how to make a CC load a webpage, instead of just an image, and then overlay the path with some js/css magic.
2. Pre-process the image before serving it (eg with imagemagic)

#1 is probably a lot cleaner, and I don't think it should be a lot of work, but it requires some experimentation. Please feel free to open a feature request (or even better, send in a pull request if you can!)
